--
-- PostgreSQL database dump
--

-- Dumped from database version 17.4
-- Dumped by pg_dump version 17.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Data for Name: artist; Type: TABLE DATA; Schema: core_tables; Owner: postgres
--

INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (1, 'florida georgia line', '3b8QkneNDz4JHKKKlLgYZg', 'https://i.scdn.co/image/ab6761610000e5ebaa2d9bd207a62adc3edf6631', 'Florida Georgia Line, a duo consisting of Tyler Hubbard and Brian Kelley, has been a major force in the country music scene since their breakout hit ''Cruise'' in 2012. They are known for blending country with elements of pop, rock, and hip-hop, which has helped them achieve widespread commercial success and influence the genre''s evolution. Their accolades include multiple Academy of Country Music Awards and a Grammy nomination, reflecting their significant impact on modern country music.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (2, 'thomas rhett', '6x2LnllRG5uGarZMsD4iO8', 'https://i.scdn.co/image/ab6761610000e5eb7538436ea7437322f6f389ca', 'Thomas Rhett has quickly risen to prominence in country music with his infectious blend of country, pop, and R&B influences. Since his debut album in 2013, he has released numerous chart-topping hits like ''Die a Happy Man'' and ''Marry Me'', showcasing his versatility and songwriting prowess. Rhett''s energetic performances and relatable lyrics have earned him multiple awards, including the Academy of Country Music''s Male Vocalist of the Year.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (3, 'lee ann womack', '738OS3zrCO782uDiUN9pet', 'https://i.scdn.co/image/ab6761610000e5eb86a12d477e7e1cb4e4b26caa', 'Lee Ann Womack is a prominent figure in country music, known for her traditional style and emotive vocals. Her breakthrough hit ''I Hope You Dance'' won multiple awards, including a Grammy for Best Country Song, and became an anthem for hope and inspiration. Womack''s dedication to preserving the roots of country music has earned her respect and admiration within the industry.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (4, 'alan jackson', '4mxWe1mtYIYfP040G38yvS', 'https://i.scdn.co/image/ab6772690000c46c1dce50b93ca0b1e2f459d9e6', 'Alan Jackson is a cornerstone of country music, celebrated for his neotraditionalist style that harks back to the genre''s roots. With hits like ''Chattahoochee'' and ''Remember When,'' he has won numerous awards, including multiple Grammys and CMA Awards. Jackson''s influence extends beyond music, as he has been inducted into the Country Music Hall of Fame.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (5, 'lonestar', '3qbnxnvUqR14MJ9g8QwZJK', 'https://i.scdn.co/image/ab6761610000e5eb1bc8cec709c2452275e53050', 'Lonestar is a country music band known for their harmonious sound and crossover success. Their hit ''Amazed'' topped both the country and pop charts, showcasing their versatility. The band''s enduring popularity is evident in their continued touring and the impact of their music on fans across generations.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (6, 'toby keith', '2bA6fzP0lMAQ4kz6CF61w8', 'https://i.scdn.co/image/ab6761610000e5eb1b6b9d83cfd806b328496207', 'Toby Keith is known for his bold, patriotic songs and his significant impact on country music. Hits like ''Courtesy of the Red, White and Blue'' and ''Red Solo Cup'' have become cultural touchstones. Keith''s entrepreneurial spirit is also notable, as he founded his own record label, Show Dog Nashville.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (7, 'jimmy buffett', '28AyklUmMECPwdfo8NEsV0', 'https://i.scdn.co/image/ab6761610000e5ebc51b2d9deea2b3cc8360828d', 'Jimmy Buffett is synonymous with the laid-back, tropical lifestyle he celebrates in his music. His song ''Margaritaville'' became a cultural phenomenon and led to a successful business empire. Buffett''s influence extends beyond music, as he has authored books and created a brand that embodies his carefree ethos.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (8, 'gretchen wilson', '0IdYRFTswLdsGwSnzOaGNF', 'https://i.scdn.co/image/ab6761610000e5ebcfcc10b18f534f720a976dc3', 'Gretchen Wilson burst onto the country scene with her hit ''Redneck Woman,'' which celebrated blue-collar pride and authenticity. Her debut album, ''Here for the Party,'' won her a Grammy for Best Female Country Vocal Performance. Wilson''s raw, unapologetic style has made her a beloved figure in country music.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (9, 'big and rich', '0oBEeN6BCxEgMogzThqrPf', 'https://i.scdn.co/image/ab6761610000e5ebc8c403161c81d8f8c02c0506', 'Big & Rich, comprised of Big Kenny and John Rich, are known for their eclectic blend of country, rock, and hip-hop. Their hit ''Save a Horse (Ride a Cowboy)'' became an anthem for their unique style. The duo''s influence extends to their founding of the MuzikMafia, a collective that fosters musical collaboration and innovation.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (10, 'sara evans', '7qvsLYsYP0MHD7jkdv6DAG', 'https://i.scdn.co/image/ab6761610000e5ebda10d709fefcb48fbdad45ad', 'Sara Evans is celebrated for her powerful vocals and heartfelt lyrics. Hits like ''Born to Fly'' and ''Suds in the Bucket'' showcase her ability to connect with audiences. Evans has been recognized with multiple awards, including the Academy of Country Music''s Top Female Vocalist.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (11, 'kenny chesney', '3grHWM9bx2E9vwJCdlRv9O', 'https://i.scdn.co/image/ab6761610000e5eb5de44c9558a47909debca2cd', 'Kenny Chesney is known for his tropical-themed songs and energetic live performances. Hits like ''No Shoes, No Shirt, No Problems'' and ''When the Sun Goes Down'' have defined his career. Chesney''s influence extends to his philanthropy, particularly through his work with the Love for Love City Foundation.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (12, 'uncle kracker', '2DnqqkzzDKm3vAoyHtn8So', 'https://i.scdn.co/image/ab6761610000e5ebae45d8ab89ad4aff41dfb021', 'Uncle Kracker, born Matthew Shafer, is known for his blend of rock, country, and hip-hop. His hit ''Follow Me'' crossed genres and showcased his versatility. Kracker''s collaboration with Kenny Chesney on ''When the Sun Goes Down'' further solidified his place in country music.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (13, 'tim mcgraw', '6roFdX1y5BYSbp60OTJWMd', 'https://i.scdn.co/image/ab6761610000e5ebbd6977f3970a7a4a8d4becbe', 'Tim McGraw is a country music icon known for his soulful voice and storytelling ability. Hits like ''Live Like You Were Dying'' and ''Humble and Kind'' have resonated with audiences worldwide. McGraw''s influence extends to his acting career and his advocacy for various social causes.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (14, 'willie nelson', '5W5bDNCqJ1jbCgTxDD0Cb3', 'https://i.scdn.co/image/ab6772690000c46c82a531f8f5067e13517f5b15', 'Willie Nelson is a legendary figure in country music, known for his distinctive voice and songwriting. Hits like ''On the Road Again'' and ''Always on My Mind'' have become classics. Nelson''s impact extends beyond music, as he is also recognized for his activism and philanthropy.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (15, 'rascal flatts', '0a1gHP0HAqALbEyxaD5Ngn', 'https://i.scdn.co/image/ab6761610000e5eb6772748e5cd3c3de721f8c03', 'Rascal Flatts is a country music trio known for their harmonious vocals and crossover success. Hits like ''Bless the Broken Road'' and ''Life is a Highway'' have become anthems. The group''s influence is evident in their numerous awards, including multiple ACM and CMA Awards.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (16, 'keith urban', '0u2FHSq3ln94y5Q57xazwf', 'https://i.scdn.co/image/ab6761610000e5eb054c067d4cfa3b8094f3400f', 'Keith Urban is known for his fusion of country and rock music, as well as his virtuoso guitar skills. Hits like ''Somebody Like You'' and ''Blue Ain''t Your Color'' have showcased his versatility. Urban''s influence extends to his work as a judge on ''American Idol'' and his advocacy for mental health.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (17, 'brandon lake', '1bdnGJxkbIIys5Jhk1T74v', 'https://i.scdn.co/image/ab6761610000e5eb8ba23cfe3ff56cc69b68f10e', 'Brandon Lake is a contemporary Christian music artist known for his worship songs. His collaboration on ''Gratitude'' with Elevation Worship has resonated with audiences worldwide. Lake''s influence extends to his work as a songwriter and his commitment to spreading faith through music.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (18, 'brad paisley', '13YmWQJFwgZrd4bf5IjMY4', 'https://i.scdn.co/image/ab6761610000e5eb49b3eca30283993e5794c6ef', 'Brad Paisley is known for his skillful guitar playing and witty songwriting. Hits like ''Whiskey Lullaby'' and ''Remind Me'' have showcased his storytelling ability. Paisley''s influence extends to his philanthropy, particularly through his work with the Country Music Hall of Fame and Museum.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (19, 'alison krauss', '5J6L7N6B4nI1M5cwa29mQG', 'https://i.scdn.co/image/ab6761610000e5eb9870f6d61fa488a37fcb58df', 'Alison Krauss is a bluegrass and country music artist known for her angelic voice and virtuoso fiddle playing. Her collaborations with Robert Plant on ''Raising Sand'' earned her multiple Grammys. Krauss''s influence extends to her work as a producer and her dedication to preserving traditional music.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (20, 'carrie underwood', '4xFUf1FHVy696Q1JQZMTRj', 'https://i.scdn.co/image/ab6761610000e5eb69084d0b776e725025329043', 'Carrie Underwood rose to fame as the winner of ''American Idol'' and has since become a powerhouse in country music. Hits like ''Before He Cheats'' and ''Jesus, Take the Wheel'' have showcased her vocal prowess. Underwood''s influence extends to her philanthropy, particularly through her work with the C.A.T.S. Foundation.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (21, 'beyonce', '6vWDO969PvNqNYHIOW5v0m', 'https://i.scdn.co/image/ab6761610000e5eb7eaa373538359164b843f7c0', 'Beyoncé is a global icon known for her powerful vocals and dynamic performances. She rose to fame as a member of Destiny''s Child before launching a successful solo career. Her album ''Lemonade'' was critically acclaimed for its thematic depth and visual storytelling, earning her numerous Grammy Awards.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (22, 'jayz', '3nFkdlSjzX9mRTtwJOzDYB', 'https://i.scdn.co/image/ab6761610000e5eb3fdebba252a8c568d3c0f7aa', 'Jay-Z, born Shawn Carter, is a legendary rapper and entrepreneur who has significantly influenced hip-hop culture. He co-founded Roc-A-Fella Records and later became the president of Def Jam Recordings. His business acumen extends to fashion with the creation of Rocawear and sports management with Roc Nation.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (23, 'kelly clarkson', '3BmGtnKgCSGYIUhmivXKWX', 'https://i.scdn.co/image/ab6761610000e5eb20b8c7d395994dc81a85f291', 'Kelly Clarkson became the first winner of ''American Idol'' and has since established herself as a versatile artist. Her powerful voice and emotional depth are showcased in hits like ''Since U Been Gone'' and ''Stronger (What Doesn''t Kill You).'' She has won multiple Grammy Awards and is known for her candid personality.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (24, 'outkast', '1G9G7WwrXka3Z1r7aIDjI7', 'https://i.scdn.co/image/ab6761610000e5eb0cb3f95b9f8f7337e135a925', 'OutKast, comprised of André 3000 and Big Boi, revolutionized Southern hip-hop with their innovative sound and eclectic style. Their album ''Speakerboxxx/The Love Below'' won the Grammy for Album of the Year, a rare feat for a hip-hop album. They are celebrated for blending genres and pushing creative boundaries.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (25, 'kanye west', '5K4W6rqBFWDnAN6FQUkS6x', 'https://i.scdn.co/image/ab6761610000e5eb6e835a500e791bf9c27a422a', 'Kanye West is a polarizing figure known for his groundbreaking music and outspoken personality. From his debut ''The College Dropout'' to ''My Beautiful Dark Twisted Fantasy,'' he has consistently pushed the boundaries of hip-hop and pop. His fashion ventures and public persona have also made significant cultural impacts.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (26, 'jamie foxx', '7LnaAXbDVIL75IVPnndf7w', 'https://i.scdn.co/image/a3823abbd476fa00cdf95a9f5cbbe09d2f96add2', 'Jamie Foxx is a multi-talented artist known for his work in music, film, and television. He won an Academy Award for Best Actor for his portrayal of Ray Charles in ''Ray.'' His music career includes hits like ''Blame It'' and collaborations with other artists across genres.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (27, 'usher', '23zg3TcAtWQy7J6upgbUnj', 'https://i.scdn.co/image/ab6761610000e5eb716114797a4a644c67c5fa72', 'Usher is a prominent R&B artist known for his smooth vocals and dynamic dance moves. His album ''Confessions'' is one of the best-selling albums of the 2000s, featuring hits like ''Yeah!'' and ''Burn.'' He has won numerous awards, including eight Grammy Awards.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (28, 'lil jon', '7sfl4Xt5KmfyDs2T3SVSMK', 'https://i.scdn.co/image/ab6761610000e5ebf893feb44e74c8b4c15ecc95', 'Lil Jon is a key figure in the crunk music scene, known for his energetic style and catchy hooks. He gained widespread fame with hits like ''Get Low'' and ''Turn Down for What.'' His influence extends to popularizing the term ''crunk'' and his work as a producer.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (29, 'black eyed peas', '1yxSLGMDHlW21z4YXirZDS', 'https://i.scdn.co/image/ab6761610000e5ebb3037310c07b99cbefbd2c6d', 'The Black Eyed Peas are a versatile group known for blending hip-hop, pop, and electronic music. Their album ''The E.N.D.'' produced global hits like ''I Gotta Feeling'' and ''Boom Boom Pow.'' They have won six Grammy Awards and are recognized for their energetic live performances.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (30, 'lady gaga', '1HY2Jd0NmPuamShAr6KMms', 'https://i.scdn.co/image/ab6761610000e5ebaadc18cac8d48124357c38e6', 'Lady Gaga is known for her bold fashion choices and powerful vocals. She rose to fame with her debut album ''The Fame,'' featuring hits like ''Just Dance'' and ''Poker Face.'' Her advocacy for the LGBTQ+ community and her philanthropy work have also made significant cultural impacts.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (31, 'rihanna', '5pKCCKE2ajJHZ9KAiaK11H', 'https://i.scdn.co/image/ab6761610000e5eb373e1be0410d4212bf72acab', 'Rihanna is a Barbadian singer and businesswoman known for her versatile music and fashion ventures. Her albums ''Good Girl Gone Bad'' and ''Anti'' have produced numerous hits, including ''Umbrella'' and ''Work.'' She has also founded successful brands like Fenty Beauty and Savage X Fenty.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (32, 'gwen stefani', '4yiQZ8tQPux8cPriYMWUFP', 'https://i.scdn.co/image/ab6761610000e5eb64b94bebbaee56f793e24853', 'Gwen Stefani first gained fame as the lead singer of No Doubt before launching a successful solo career. Her album ''Love. Angel. Music. Baby.'' featured hits like ''Hollaback Girl'' and ''Rich Girl.'' She is also known for her fashion line L.A.M.B. and her work as a coach on ''The Voice.''', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (33, 'britney spears', '26dSoYclwsYLMAKD3tpOr4', 'https://i.scdn.co/image/ab6761610000e5eb26e59b825251b7df20a7b65e', 'Britney Spears is a pop icon known for her catchy songs and iconic performances. Her debut album ''...Baby One More Time'' launched her to stardom, and she has since released numerous hits like ''Toxic'' and ''Oops!... I Did It Again.'' Her influence on pop culture and music is undeniable.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (34, 'flo rida', '0jnsk9HBra6NMjO2oANoPY', 'https://i.scdn.co/image/ab6761610000e5eb655ca8f3196953554b479452', 'Flo Rida is known for his infectious club anthems and collaborations with various artists. His hits include ''Low,'' ''Right Round,'' and ''Club Can''t Handle Me.'' He has a knack for blending hip-hop and pop, making him a staple in the music industry.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (35, 'tpain', '3aQeKQSyrW4qWr35idm0cy', 'https://i.scdn.co/image/ab6761610000e5ebeac6cf38775b541255dc13a6', 'T-Pain is famous for popularizing the use of Auto-Tune in his music. His hits include ''Buy U a Drank (Shawty Snappin'')'' and ''Bartender.'' He has won two Grammy Awards and is known for his unique vocal style and production work.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (36, 'leona lewis', '5lKZWd6HiSCLfnDGrq9RAm', 'https://i.scdn.co/image/ab6761610000e5ebe9cf3862b8027eb5b9f6b831', 'Leona Lewis rose to fame after winning ''The X Factor'' in the UK. Her debut album ''Spirit'' featured the hit ''Bleeding Love,'' which became an international success. She is known for her powerful vocals and has since released several successful albums.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (37, '50 cent', '3q7HBObVc0L8jNeTe5Gofh', 'https://i.scdn.co/image/dd031b9c5d1b6eba4a691cd89c954255aae787f2', '50 Cent, born Curtis Jackson, is known for his gritty lyrics and entrepreneurial spirit. His debut album ''Get Rich or Die Tryin'''' was a massive success, featuring hits like ''In da Club.'' He has also ventured into acting and founded the successful liquor brand, Sire Spirits.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (38, 'olivia', '5YBSzuCs7WaFKNr7Bky0Uf', 'https://i.scdn.co/image/ab6761610000e5ebe03a98785f3658f0b6461ec4', 'Olivia is an R&B singer who gained fame with her hit ''Bizounce.'' She was signed to J Records and later collaborated with 50 Cent on ''Candy Shop.'' Her powerful voice and stage presence have made her a notable figure in the music industry.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (39, 'colby odonis', '7fObcBw9VM3x7ntWKCYl0z', 'https://i.scdn.co/image/ab6761610000e5eb2c44e078944196a8c1eec256', 'Colby O''Donis is known for his collaborations with other artists, including Lady Gaga on ''Just Dance.'' His smooth vocals and R&B style have earned him a place in the music industry. He has also released solo work, showcasing his versatility.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (40, 'lil wayne', '55Aa2cqylxrFIXC767Z865', 'https://i.scdn.co/image/ab6761610000e5eb998010cd1075921b5faf16b2', 'Lil Wayne, born Dwayne Carter Jr., is a prolific rapper known for his mixtape series and albums like ''Tha Carter III.'' He has won multiple Grammy Awards and is celebrated for his unique flow and lyrical prowess. His influence on hip-hop is extensive.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (41, 'static major', '3pbi8H08p95NUZ7m6ybxUV', 'https://i.scdn.co/image/ab6761610000e5eb5ccc476e8b18673e01d87420', 'Static Major, born Stephen Garrett, was a talented singer and songwriter known for his work with Aaliyah and Ginuwine. He co-wrote the hit ''Lollipop'' for Lil Wayne, which became a posthumous success after his untimely death. His contributions to R&B and hip-hop are significant.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (42, 'nelly', '2gBjLmx6zQnFGQJCAQpRgw', 'https://i.scdn.co/image/3677690af58abb70a5c5fd58d69db4d1ad705d4f', 'Nelly is known for his unique rap style and catchy hooks. His debut album ''Country Grammar'' featured the hit ''Ride wit Me,'' and he has since released numerous successful albums. He is also recognized for his philanthropy work and business ventures.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (43, 'sean paul', '3Isy6kedDrgPYoTS1dazA9', 'https://i.scdn.co/image/ab6761610000e5eb60c3e9abe7327c0097738f22', 'Sean Paul is a Jamaican dancehall artist known for his distinctive voice and infectious rhythms. His hits include ''Temperature'' and ''Get Busy,'' which have crossed over into mainstream pop. He has won a Grammy Award and is a major figure in the dancehall genre.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (44, 'katy perry', '6jJ0s89eD6GaHleKKya26X', 'https://i.scdn.co/image/ab6761610000e5eb0988562f78810e47a6e3325f', 'Katy Perry is known for her colorful pop music and theatrical performances. Her album ''Teenage Dream'' produced multiple number-one hits, including ''Firework'' and ''California Gurls.'' She is also recognized for her advocacy work and her role as a judge on ''American Idol.''', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (45, 'kesha', '6LqNN22kT3074XbTVUrhzX', 'https://i.scdn.co/image/ab6761610000e5eb1c43cbfb50d7ac393df96ae5', 'Kesha is known for her party anthems and unique vocal style. Her debut album ''Animal'' featured hits like ''Tik Tok'' and ''Your Love Is My Drug.'' She has since released more personal and introspective work, showcasing her versatility as an artist.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (46, 'taio cruz', '6MF9fzBmfXghAz953czmBC', 'https://i.scdn.co/image/ab6761610000e5eb153171480a6f22912253b9f1', 'Taio Cruz is a British singer-songwriter known for his pop and R&B hits. His songs ''Break Your Heart'' and ''Dynamite'' became international successes. He is also recognized for his work as a producer and songwriter for other artists.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (47, 'taylor swift', '06HL4z0CvFAxyc27GXpf02', 'https://i.scdn.co/image/ab6761610000e5ebe672b5f553298dcdccb0e676', 'Taylor Swift is known for her narrative songwriting and genre versatility. She began her career in country music before transitioning to pop with albums like ''1989'' and ''Reputation.'' Her influence extends to her advocacy for artists'' rights and her philanthropy work.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (48, 'alicia keys', '3DiDSECUqqY1AuBP8qtaIa', 'https://i.scdn.co/image/ab6761610000e5ebebfd16a3bca87c31c1e20576', 'Alicia Keys is known for her soulful voice and piano skills. Her debut album ''Songs in A Minor'' featured the hit ''Fallin'','' and she has since released numerous successful albums. She is also recognized for her advocacy work and her role as a judge on ''The Voice.''', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (49, 'shakira', '0EmeFodog0BfCgMzAIvKQp', 'https://i.scdn.co/image/ab6761610000e5eb2528c726e5ddb90a7197e527', 'Shakira is a Colombian singer known for her unique voice and dance moves. Her hits include ''Hips Don''t Lie'' and ''Whenever, Wherever.'' She is also recognized for her philanthropy work, particularly through her Pies Descalzos Foundation.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (50, 'wyclef jean', '7aBzpmFXB4WWpPl2F7RjBe', 'https://i.scdn.co/image/ab6761610000e5ebad53e714cc3481bd069bfc93', 'Wyclef Jean is a Haitian-American musician known for his work with the Fugees and his solo career. His hits include ''Gone Till November'' and ''Sweetest Girl (Dollar Bill).'' He is also recognized for his philanthropy work and his political activism.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (51, 'justin timberlake', '31TPClRtHm23RisEBtV3X7', 'https://i.scdn.co/image/ab6761610000e5eb7a5cfe2597665a3d160e805e', 'Justin Timberlake is known for his smooth vocals and dynamic performances. He rose to fame with NSYNC before launching a successful solo career. His albums ''Justified'' and ''FutureSex/LoveSounds'' produced hits like ''Cry Me a River'' and ''SexyBack.''', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (52, 'timbaland', '5Y5TRrQiqgUO4S36tzjIRZ', 'https://i.scdn.co/image/ab6761610000e5ebb713079a55dcf937d241dd2b', 'Timbaland is a renowned producer and rapper known for his innovative beats and collaborations. He has worked with artists like Aaliyah, Missy Elliott, and Justin Timberlake. His production style has significantly influenced the sound of modern pop and hip-hop.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (53, 'nelly furtado', '2jw70GZXlAI8QzWeY2bgRc', 'https://i.scdn.co/image/ab6761610000e5ebd2ce0bf5614b54bd44e059d5', 'Nelly Furtado is known for her versatile music style, blending pop, folk, and hip-hop. Her album ''Loose'' featured hits like ''Promiscuous'' and ''Maneater.'' She is also recognized for her multilingual abilities and her advocacy for social issues.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (54, 'avril lavigne', '0p4nmQO2msCgU4IF37Wi3j', 'https://i.scdn.co/image/ab6761610000e5ebcea575e8c9519d4367984256', 'Avril Lavigne is known for her punk-influenced pop music and rebellious image. Her debut album ''Let Go'' featured hits like ''Complicated'' and ''Sk8er Boi.'' She has since released several successful albums and is recognized for her songwriting skills.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (55, 'mary j blige', '1XkoF8ryArs86LZvFOkbyr', 'https://i.scdn.co/image/ab6761610000e5eb3d7888ba4d2bf67fe6b64a55', 'Mary J. Blige is known as the ''Queen of Hip-Hop Soul'' for her fusion of R&B and hip-hop. Her album ''My Life'' is considered a classic, and she has won numerous Grammy Awards. Her powerful vocals and emotional depth have made her a legendary figure in music.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (56, 'snoop dogg', '7hJcb9fa4alzcOq3EaNPoG', 'https://i.scdn.co/image/ab6761610000e5ebc19a88576ebe6fcbb325c297', 'Snoop Dogg, born Calvin Broadus Jr., is a legendary rapper known for his laid-back style and distinctive voice. His debut album ''Doggystyle'' was a massive success, and he has since released numerous albums and collaborated with various artists. He is also recognized for his ventures into acting and business.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (57, 'pharrell williams', '2RdwBSPQiwcmiDo9kixcl8', 'https://i.scdn.co/image/ab6761610000e5ebf0789cd783c20985ec3deb4e', 'Pharrell Williams is a multi-talented artist known for his work as a singer, producer, and fashion designer. His hits include ''Happy'' and ''Blurred Lines,'' and he has won multiple Grammy Awards. His production work with The Neptunes has significantly influenced modern music.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (58, 'eminem', '7dGJo4pcD2V6oG8kP0tJRR', 'https://i.scdn.co/image/ab6761610000e5eba00b11c129b27a88fc72f36b', 'Eminem, born Marshall Mathers, is known for his rapid-fire delivery and controversial lyrics. His albums ''The Marshall Mathers LP'' and ''The Eminem Show'' are considered classics, and he has won numerous Grammy Awards. His influence on hip-hop and pop culture is undeniable.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (59, 'coldplay', '4gzpq5DPGxSnKTe4SA8HAU', 'https://i.scdn.co/image/ab6761610000e5eb1ba8fc5f5c73e7e9313cc6eb', 'Coldplay is known for their anthemic rock sound and introspective lyrics. Their album ''A Rush of Blood to the Head'' featured hits like ''Clocks'' and ''The Scientist.'' They have won multiple Grammy Awards and are recognized for their live performances and philanthropy work.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (60, 'snow patrol', '3rIZMv9rysU7JkLzEaC5Jp', 'https://i.scdn.co/image/ab6761610000e5eb9b328846dc38b0a620da1ce2', 'Snow Patrol is known for their emotive rock music and heartfelt lyrics. Their album ''Eyes Open'' featured the hit ''Chasing Cars,'' which became a global success. They have won multiple awards and are recognized for their live performances and songwriting.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (61, 'the fray', '0zOcE3mg9nS6l3yxt1Y0bK', 'https://i.scdn.co/image/ab6761610000e5ebfbde447822e329707f1c4ea3', 'The Fray is known for their piano-driven rock sound and emotional lyrics. Their debut album featured the hit ''How to Save a Life,'' which became a cultural phenomenon. They have won multiple awards and are recognized for their live performances and songwriting.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (62, 'nickelback', '6deZN1bslXzeGvOLaLMOIF', 'https://i.scdn.co/image/ab6761610000e5eb4ad382f899596d8c7b9e8e09', 'Nickelback, formed in 1995, is a Canadian rock band known for their mainstream success with hits like ''How You Remind Me'' and ''Photograph.'' Despite being one of the best-selling acts of the 2000s, they have faced significant criticism and internet memes, which has become a part of their cultural legacy. Their music often blends hard rock with post-grunge elements, appealing to a broad audience.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (63, 'linkin park', '6XyY86QOPPrYVGvF9ch6wz', 'https://i.scdn.co/image/ab6761610000e5eb527d95dabbe8b8b527e8136f', 'Linkin Park, formed in 1996, revolutionized the nu-metal genre with their debut album ''Hybrid Theory,'' which included hits like ''In the End'' and ''One Step Closer.'' The band''s fusion of rock, hip-hop, and electronic music has influenced countless artists. Tragically, the loss of lead vocalist Chester Bennington in 2017 marked a significant moment in their history, yet their legacy continues to inspire fans worldwide.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (64, 'green day', '7oPftvlwr6VrsViSDV7fJY', 'https://i.scdn.co/image/ab6761610000e5eb6ff0cd5ef2ecf733804984bb', 'Green Day, formed in 1987, is a punk rock band that gained mainstream success with their album ''Dookie'' in 1994. Their politically charged album ''American Idiot'' in 2004 revitalized their career and earned them a Grammy Award for Best Rock Album. Known for their energetic live performances and catchy melodies, Green Day has been a significant influence on pop-punk and alternative rock.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (65, 'red hot chili peppers', '0L8ExT028jH3ddEcZwqJJ5', 'https://i.scdn.co/image/ab6761610000e5ebc33cc15260b767ddec982ce8', 'Red Hot Chili Peppers, formed in 1983, are known for their unique blend of funk, punk, and rock music. With iconic albums like ''Blood Sugar Sex Magik'' and hits like ''Under the Bridge,'' they have achieved widespread acclaim and multiple Grammy Awards. Their energetic performances and innovative style have made them one of the most influential bands in alternative rock.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (66, '3 doors down', '2RTUTCvo6onsAnheUk3aL9', 'https://i.scdn.co/image/ab6761610000e5eb2064b57344edc592454c8090', '3 Doors Down, formed in 1996, gained fame with their debut single ''Kryptonite,'' which became a rock staple. Their music often explores themes of personal struggle and resilience, resonating with a wide audience. The band has continued to release successful albums and tour extensively, maintaining a strong fan base.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (67, 'papa roach', '4RddZ3iHvSpGV4dvATac9X', 'https://i.scdn.co/image/ab6761610000e5eb170958adc93250084c317cfc', 'Papa Roach, formed in 1993, broke into the mainstream with their album ''Infest,'' featuring the hit ''Last Resort.'' Known for their nu-metal sound and later forays into alternative rock, they have maintained a dedicated following. Their music often addresses personal and social issues, making them a significant voice in the rock scene.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (68, 'the white stripes', '4F84IBURUo98rz4r61KF70', 'https://i.scdn.co/image/ab6761610000e5eb70cc06de8fc28226d4743cd9', 'The White Stripes, formed by Jack and Meg White in 1997, are known for their minimalist approach to rock music, often using only guitar, drums, and vocals. Their album ''Elephant'' and the hit ''Seven Nation Army'' have become iconic in the rock genre. The band''s influence extends beyond music, impacting fashion and art with their distinctive red, white, and black aesthetic.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (69, 'the killers', '0C0XlULifJtAgn6ZNCW2eu', 'https://i.scdn.co/image/ab6761610000e5eb207b21f3ed0ee96adce3166a', 'The Killers, formed in 2001, are known for their synth-infused rock sound and catchy hits like ''Mr. Brightside'' and ''Somebody Told Me.'' Their debut album ''Hot Fuss'' became a commercial success, and they have since released several acclaimed albums. The band''s ability to blend new wave, indie, and pop elements has made them a staple in modern rock music.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (70, 'train', '3FUY2gzHeIiaesXtOAdB7A', 'https://i.scdn.co/image/ab6761610000e5ebeb96a88993a929eaadbe4864', 'Train, formed in 1993, achieved mainstream success with their hit ''Drops of Jupiter (Tell Me),'' which won two Grammy Awards. Known for their melodic rock and pop sound, they have continued to release popular songs like ''Hey, Soul Sister.'' Their music often features introspective lyrics and catchy hooks, appealing to a broad audience.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (71, 'lifehouse', '5PokPZn11xzZXyXSfnvIM3', 'https://i.scdn.co/image/ab6761610000e5eb621cdc23c3db9d37d780762e', 'Lifehouse, formed in 1999, gained fame with their debut single ''Hanging by a Moment,'' which became a defining song of the early 2000s. Their music blends rock and pop elements, often focusing on themes of love and personal growth. The band has maintained a loyal fan base and continues to release new music.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (72, 'jimmy eat world', '3Ayl7mCk0nScecqOzvNp6s', 'https://i.scdn.co/image/ab6761610000e5eb0dc33cfd207772f8e2f6b46f', 'Jimmy Eat World, formed in 1993, became known for their emo and alternative rock sound, particularly with their hit ''The Middle.'' Their album ''Bleed American'' solidified their place in the music scene, and they have since released several successful albums. Known for their catchy melodies and introspective lyrics, they have influenced many bands in the emo genre.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (73, 'panic at the disco', '20JZFwl6HVl6yg8a4H3ZqK', 'https://i.scdn.co/image/ab6761610000e5ebb256ae9a4b82bfff97776ae2', 'Panic! at the Disco, formed in 2004, gained fame with their debut album ''A Fever You Can''t Sweat Out'' and the hit ''I Write Sins Not Tragedies.'' The band''s music has evolved from emo and pop-punk to a more pop-oriented sound. Led by frontman Brendon Urie, they have continued to release successful albums and maintain a strong fan base.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (74, 'gorillaz', '3AA28KZvwAUcZuOKwyblJQ', 'https://i.scdn.co/image/ab6761610000e5eb8699856fde13105fa01279ad', 'Gorillaz, created by Damon Albarn and Jamie Hewlett in 1998, is a virtual band known for their innovative blend of alternative rock, hip-hop, and electronic music. Their debut album ''Gorillaz'' and hits like ''Clint Eastwood'' have been critically acclaimed. The band''s use of animated characters and storytelling has set them apart in the music industry.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (75, 'de la soul', '1Z8ODXyhEBi3WynYw0Rya6', 'https://i.scdn.co/image/ab6761610000e5ebc443011311dcf7f6eeaf507d', 'De La Soul, formed in 1987, is known for their debut album ''3 Feet High and Rising,'' which introduced a new style of hip-hop with its eclectic sampling and positive lyrics. They have been influential in the development of alternative hip-hop and have won a Grammy Award for Best Pop Collaboration with Vocals. Their innovative approach to music and culture continues to inspire new generations.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (76, 'shaun ryder', '3ONSkkEnOSZVNogu98dvTY', 'https://i.scdn.co/image/ab6772690000c46cd7bc7201def92f45d79cabbe', 'Shaun Ryder, known for his work with Happy Mondays and Black Grape, is a key figure in the Madchester scene of the late 1980s and early 1990s. His distinctive vocal style and provocative lyrics have made him a cult icon. Ryder''s influence extends beyond music, as he has also appeared on reality TV shows, showcasing his unique personality.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (77, 'foo fighters', '7jy3rLJdDQY21OgRLCZ9sD', 'https://i.scdn.co/image/ab6761610000e5eb07be1890ac379235723258de', 'Foo Fighters, formed by Dave Grohl in 1994, emerged from the ashes of Nirvana to become one of the most successful rock bands of the 2000s. Known for hits like ''Everlong'' and ''Learn to Fly,'' they have won multiple Grammy Awards. Their music blends hard rock with melodic elements, appealing to a wide audience.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (78, 'hoobastank', '2MqhkhX4npxDZ62ObR5ELO', 'https://i.scdn.co/image/ab6761610000e5ebb6f14120a7c97c531c2ebdcc', 'Hoobastank, formed in 1994, gained fame with their hit ''The Reason,'' which became a defining song of the early 2000s. Their music blends alternative rock with post-grunge elements, often focusing on themes of personal struggle and redemption. The band has continued to release music and tour, maintaining a dedicated fan base.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (79, 'evanescence', '5nGIFgo0shDenQYSE0Sn7c', 'https://i.scdn.co/image/ab6761610000e5eb7ecf213c7dd78e0049379c5b', 'Evanescence, formed in 1995, gained fame with their debut album ''Fallen'' and the hit ''Bring Me to Life.'' Known for their blend of gothic rock and symphonic elements, they have won multiple awards, including two Grammy Awards. The band''s music often explores themes of personal struggle and empowerment, resonating with a wide audience.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (80, 'system of a down', '5eAWCfyUhZtHHtBdNk56l1', 'https://i.scdn.co/image/ab6761610000e5eb60063d3451ade8f9fab397c2', 'System of a Down, formed in 1994, is known for their unique blend of alternative metal, hard rock, and Armenian folk music. Their politically charged lyrics and hits like ''Chop Suey!'' and ''B.Y.O.B.'' have earned them a dedicated following. The band has won a Grammy Award and continues to influence the rock genre.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (81, 'franz ferdinand', '0XNa1vTidXlvJ2gHSsRi4A', 'https://i.scdn.co/image/ab6761610000e5eb69ecfa7557856564c968640d', 'Franz Ferdinand, formed in 2002, gained fame with their debut album and the hit ''Take Me Out.'' Known for their post-punk revival sound, they have won multiple awards, including a Mercury Prize. Their music often features catchy melodies and danceable rhythms, making them a staple in indie rock.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (82, 'yeah yeah yeahs', '3TNt4aUIxgfy9aoaft5Jj2', 'https://i.scdn.co/image/ab6761610000e5eb746654923d25b6bf7c16e899', 'Yeah Yeah Yeahs, formed in 2000, are known for their art punk and indie rock sound, with hits like ''Maps'' and ''Heads Will Roll.'' Led by frontwoman Karen O, they have been influential in the indie scene and have won a Grammy Award. Their music often blends raw energy with emotional depth, resonating with fans.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (83, 'modest mouse', '1yAwtBaoHLEDWAnWR87hBT', 'https://i.scdn.co/image/ab6761610000e5eb39b413eb76d2ae87496d76b8', 'Modest Mouse, formed in 1992, gained fame with their album ''Good News for People Who Love Bad News'' and the hit ''Float On.'' Known for their indie rock sound and introspective lyrics, they have been influential in the indie scene. The band''s music often explores themes of existentialism and social commentary.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (84, 'maroon 5', '04gDigrS5kc9YWfZHwBETP', 'https://i.scdn.co/image/ab6761610000e5ebf8349dfb619a7f842242de77', 'Maroon 5, formed in 1994, gained fame with their debut album ''Songs About Jane'' and hits like ''This Love'' and ''She Will Be Loved.'' Known for their pop-rock sound and catchy melodies, they have won multiple Grammy Awards. The band''s music often features themes of love and relationships, appealing to a broad audience.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (85, 'the rembrandts', '0gDg7FEsF4Y1jWddJJgcn4', 'https://i.scdn.co/image/ab6761610000e5eb203cbc1f8dbeac5b4993581a', 'The Rembrandts are an American pop rock duo best known for their hit song ''I''ll Be There for You,'' which served as the theme song for the television sitcom Friends. Their music often blends elements of pop and rock, with catchy melodies and harmonies. The success of ''I''ll Be There for You'' significantly boosted their career, leading to increased recognition and a lasting legacy in pop culture.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (86, 'gary portnoy', '53U1IJqr6Hhmn53UcbgF7D', 'https://i.scdn.co/image/ab67616d0000b2736bb85ed5053d24308e49d961', 'Gary Portnoy is an American singer-songwriter famous for co-writing and performing the theme songs for the television shows Cheers and Punky Brewster. His work on ''Where Everybody Knows Your Name'' for Cheers earned him a Primetime Emmy Award nomination. Portnoy''s contributions to television themes have left a lasting impact on the genre, blending catchy tunes with memorable lyrics.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (87, 'dj jazzy jeff and the fresh prince', '1mG23iQeR29Ojhq89D5gbh', 'https://i.scdn.co/image/3194246bd54b76c376e2be5a21a61dd7b93aeeb9', 'DJ Jazzy Jeff & The Fresh Prince, consisting of DJ Jazzy Jeff and Will Smith, were pioneers in the hip-hop genre, known for their light-hearted and comedic approach to music. They won the first-ever Grammy Award for Best Rap Performance in 1989 for their hit ''Parents Just Don''t Understand.'' Their influence extended beyond music, with Will Smith''s successful transition to acting, impacting both music and entertainment industries.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (88, 'andrew gold', '5fmvGUlMVgmnCn45f1he7d', 'https://i.scdn.co/image/ab6761610000e5eb5b80adaab28dc1d9bc464eaf', 'Andrew Gold was an American singer, songwriter, and musician known for his hit singles ''Lonely Boy'' and ''Thank You for Being a Friend,'' the latter becoming the theme song for The Golden Girls. His versatile musical style ranged from pop to rock, and he was also a skilled session musician, contributing to albums by artists like Linda Ronstadt. Gold''s work has left a lasting legacy in both the pop and television music genres.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (89, 'janet dubois', '1Cj6mWmO7c0HBuHNGSmOOg', 'https://i.scdn.co/image/ab67616d0000b273dc65e384a8fb04cf07775e02', 'Janet DuBois was an American actress and singer best known for her role as Willona Woods on the television show Good Times. She also wrote and performed the theme song for The Jeffersons, ''Movin'' On Up,'' which became a cultural phenomenon. DuBois'' contributions to television and music have cemented her place in entertainment history.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (90, 'jeff barry', '4h4nyO6EOTwCGe7LwwHR4I', 'https://i.scdn.co/image/ffcb330904f039341a64c00f8c4cc4a853fa5f70', 'Jeff Barry is an American pop music songwriter, singer, and record producer known for co-writing numerous hit songs in the 1960s, including ''Sugar Town'' and ''I''m a Believer.'' His work with Ellie Greenwich produced many classic tracks that defined the era''s pop sound. Barry''s influence on pop music is profound, with his songs continuing to be celebrated and covered by artists across generations.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (91, 'the brady bunch', '1b5kd4esL2zG9nhXz65b8K', 'https://i.scdn.co/image/ab67616d0000b2734cc5ae1a7de063cb700b725d', 'The Brady Bunch was a fictional family from the popular 1970s television show of the same name, who also released several albums and singles. Their most famous song, ''Sunshine Day,'' captured the wholesome and upbeat spirit of the show. The Brady Bunch''s music has become a nostalgic part of pop culture, often remembered fondly by fans of the series.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (92, 'jack marshall', '3Aph9hft9LO5087r28M3MZ', 'https://i.scdn.co/image/ab6761610000e5eb51b788e4c730718fff40fa4c', 'Jack Marshall was an American guitarist, conductor, and composer known for his work on television themes, including the theme for The Munsters. He was a prolific session musician and arranger, contributing to numerous recordings across various genres. Marshall''s distinctive guitar work and compositions have left a lasting impact on the sound of television in the 1960s.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (93, 'flatt and scruggs', '1iNNWK8bYjc5EK0waLk1J1', 'https://i.scdn.co/image/02b9a077c9972ca7d79069f1485da39e82634af4', 'Flatt and Scruggs were an influential American bluegrass duo, consisting of Lester Flatt and Earl Scruggs. They are best known for their theme song for The Beverly Hillbillies, ''The Ballad of Jed Clampett,'' which became a crossover hit. Their innovative style and virtuosity on the banjo and guitar helped define and popularize bluegrass music.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (94, 'earle hagen', '2yAjgGMoWrfjWXnZ63ynP5', 'https://i.scdn.co/image/ab67616d0000b273f79eb984a5d87231fa8a6ea1', 'Earle Hagen was an American composer best known for creating the themes for The Andy Griffith Show and The Dick Van Dyke Show. His work in television music earned him multiple Emmy Awards, and his themes are some of the most recognizable in television history. Hagen''s contributions to the genre have had a lasting impact on the sound of classic TV shows.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (95, 'marius constant', '0TFFISao0xA2ax2vkzbN0l', 'https://i.scdn.co/image/ab67616d0000b27311c0f478c6f6f61bd5641c2e', 'Marius Constant was a Romanian-born French composer known for creating the iconic theme for The Twilight Zone. His work in film and television music blended classical and modern elements, creating a unique and haunting sound. Constant''s theme for The Twilight Zone remains one of the most recognized and influential pieces in television history.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (96, 'boston pops orchestra', '7CIcEIOiWaZcEH35cpsdZq', 'https://i.scdn.co/image/ab6761610000e5ebabee00ff8d2e08f97d7d1ac7', 'The Boston Pops Orchestra is an American orchestra based in Boston, Massachusetts, known for its performances of popular and light classical music. They have recorded numerous television themes, including the theme for The Lawrence Welk Show. The Boston Pops'' contributions to television music have helped bridge the gap between classical and popular music, bringing orchestral arrangements to a wider audience.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (97, 'the ventures', '2GaayiIs1kcyNqRXQuzp35', 'https://i.scdn.co/image/ab6761610000e5eb48d2552358f9c87c67f21d55', 'The Ventures are an American instrumental rock band known for their hit ''Walk, Don''t Run,'' which became a surf rock classic. They have also recorded numerous television themes, including the theme for Hawaii Five-O. The Ventures'' influence on instrumental rock and their prolific output of television themes have cemented their place in music history.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (98, 'lalo schifrin', '39iHRO9MH9To3gjW7wqaW1', 'https://i.scdn.co/image/eb76a42d736645df1fd87f88e9dc57297a181698', 'Lalo Schifrin is an Argentine-American composer, conductor, and pianist known for his work on film and television scores, including the theme for Mission: Impossible. His innovative use of jazz and Latin elements in his compositions has earned him multiple Grammy and Emmy Awards. Schifrin''s work has had a significant impact on the sound of action and thriller genres.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (99, 'henry mancini', '2EExdpjU4SK3xnJHO5paJf', 'https://i.scdn.co/image/ab6761610000e5eb9ee0e74df9f9ee5745caf24c', 'Henry Mancini was an American composer and conductor known for his iconic film and television scores, including the themes for The Pink Panther and Peter Gunn. His work earned him numerous Academy and Grammy Awards, and his compositions are celebrated for their sophistication and catchiness. Mancini''s influence on film and television music is profound, with his themes remaining popular and influential.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (100, 'walter schumann', '3867gCebd7mtrAXTgWV3kU', NULL, 'Walter Schumann was an American composer and conductor known for creating the theme for the television series Dragnet. His work in television and film music helped define the sound of crime dramas in the 1950s. Schumann''s theme for Dragnet is one of the most recognizable and influential pieces in television history.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (101, 'ray anthony and his orchestra', '5QW6Fuf8rC85McLea15MaK', 'https://i.scdn.co/image/ab67616d0000b2731994b0cd05a5a981c78c946c', 'Ray Anthony and His Orchestra are an American big band known for their renditions of popular songs and television themes, including the theme for Peter Gunn. Their music blends elements of swing and jazz, creating a lively and danceable sound. Ray Anthony''s contributions to television music have helped keep the big band sound alive in popular culture.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (102, 'plas johnson', '4Xqx9yiQsWMNXE2oKbm5uc', 'https://i.scdn.co/image/9cca5075c47514a22fac9ce2d5f04640d5752620', 'Plas Johnson is an American saxophonist known for his work on numerous television themes, including the theme for The Pink Panther. His distinctive saxophone sound has been featured on countless recordings across various genres. Johnson''s contributions to television music have helped define the sound of many classic TV shows.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (103, 'neal hefti', '3IjVHk8Mo8GBMKyHnwmth8', 'https://i.scdn.co/image/ab67616d0000b273fbdd11fc5c3be27892bdc496', 'Neal Hefti was an American jazz trumpeter, composer, and arranger known for creating the themes for The Odd Couple and Batman. His work in television and film music blended jazz and pop elements, creating catchy and memorable themes. Hefti''s influence on television music is significant, with his themes remaining popular and iconic.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (104, 'alexander courage', '2qLGUeF6YNEfR2lyzY6Nah', 'https://i.scdn.co/image/ab67616d0000b2730edc5013d2cf80371d904dbc', 'Alexander Courage was an American orchestrator, arranger, and composer known for creating the theme for Star Trek. His work in film and television music earned him multiple Emmy Awards, and his themes are some of the most recognizable in science fiction. Courage''s contributions to the genre have had a lasting impact on the sound of space exploration in media.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (105, 'fred steiner', '7IL5hGayYCP22e908cdChk', 'https://i.scdn.co/image/ab67616d0000b27349fdfbdf1bcbe3392e895f7b', 'Fred Steiner was an American composer, conductor, and orchestrator known for his work on television themes, including the theme for Perry Mason. His compositions often blended classical and modern elements, creating a unique and memorable sound. Steiner''s contributions to television music have helped define the sound of many classic TV shows.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (106, 'danny elfman', '5qBZETtyzfYnXOobDXbmcD', 'https://i.scdn.co/image/ab6761610000e5ebf741706530dbd36d43078b98', 'Danny Elfman is an American composer, singer, and songwriter known for his work on film and television scores, including the themes for The Simpsons and Batman. His distinctive style blends elements of rock, pop, and classical music, creating memorable and iconic themes. Elfman''s influence on film and television music is profound, with his themes remaining popular and influential.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (107, 'the city of prague philharmonic orchestra', '2oQJQUIpJFFnfKvHJA0xBu', 'https://i.scdn.co/image/ab6761610000e5eb8c6007c4950dd2361e50be9a', 'The City of Prague Philharmonic Orchestra is a Czech orchestra known for its recordings of film and television scores, including themes for various movies and TV shows. Their work has helped bring orchestral arrangements to a wider audience, bridging the gap between classical and popular music. The City of Prague Philharmonic''s contributions to television music have been significant, with their recordings being used in numerous productions.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (108, 'mark snow', '0JG0Qap3zA5NciJOzIalt3', 'https://i.scdn.co/image/3aaf8bd64f082c24247067aa4afb6f705a2d7389', 'Mark Snow is an American composer known for creating the theme for The X-Files. His work in television and film music blends elements of electronic and orchestral music, creating a unique and haunting sound. Snow''s contributions to the genre have had a lasting impact on the sound of science fiction and mystery in media.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (109, 'mike post', '2roaPGR1goiiLQxrG5dXiF', 'https://i.scdn.co/image/ab6761610000e5ebbfab18ee720b5158673f4e08', 'Mike Post is an American composer and record producer known for creating themes for numerous television shows, including The A-Team and Law & Order. His work in television music has earned him multiple Emmy Awards, and his themes are some of the most recognizable in the genre. Post''s influence on television music is significant, with his themes remaining popular and influential.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (110, 'the who', '67ea9eGLXYMsO2eYQRui3w', 'https://i.scdn.co/image/9cd709cabb4a614b4f1dd9ec256a5f30e21f0150', 'The Who are an English rock band known for their hit songs ''My Generation'' and ''Baba O''Riley,'' the latter of which was used as the theme for CSI: Crime Scene Investigation. Their music blends elements of rock, pop, and experimental sounds, creating a unique and influential style. The Who''s contributions to rock music and their use in television themes have cemented their place in music history.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (111, 'alabama 3', '25zUD40u8M2kJmdcabBzrz', 'https://i.scdn.co/image/ab6761610000e5eb5ae7890c4d13f635f5117e94', 'Alabama 3 are a British band known for their eclectic style, blending elements of rock, electronica, and country. They are best known for their song ''Woke Up This Morning,'' which was used as the theme for The Sopranos. Alabama 3''s unique sound and their contribution to television music have made them a notable presence in the music industry.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (112, 'wg snuffy walden', '1o9c8sfXo2HKF95bWvPUbN', 'https://i.scdn.co/image/ab67616d0000b2739ed595fe03a14d749ed56658', 'W.G. Snuffy Walden is an American composer and musician known for creating the themes for The West Wing and My So-Called Life. His work in television music blends elements of rock and orchestral music, creating a unique and memorable sound. Walden''s contributions to the genre have had a lasting impact on the sound of drama and political shows.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (113, 'james newton howard', '2M4eNCvV3CJUswavkhAQg2', 'https://i.scdn.co/image/ab6761610000e5ebe9d190a9e39a772d84b068ab', 'James Newton Howard is an American composer known for his work on film and television scores, including the themes for ER and Pretty Woman. His compositions often blend elements of orchestral and electronic music, creating a sophisticated and emotive sound. Howard''s influence on film and television music is significant, with his themes remaining popular and influential.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (114, 'phantom planet', '0LsTFjEB1IIrh7IlTxs1GY', 'https://i.scdn.co/image/ab6761610000e5eb7a0c1e8ecd58c1fdede23a25', 'Phantom Planet are an American rock band known for their hit song ''California,'' which was used as the theme for The O.C. Their music blends elements of pop and rock, creating a catchy and energetic sound. Phantom Planet''s contribution to television music has helped define the sound of teen dramas in the early 2000s.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (115, 'lazlo bane', '2jI9rHOuUAPJEULovOfgyB', 'https://i.scdn.co/image/ab6761610000e5eb1290ac08174212090f41ac5d', 'Lazlo Bane are an American alternative rock band known for their song ''Superman,'' which was used as the theme for Scrubs. Their music blends elements of rock and pop, creating a catchy and uplifting sound. Lazlo Bane''s contribution to television music has helped define the sound of medical comedies.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (116, 'the scrantones', '7kTw12ClOvpgRqtogHeG3J', 'https://i.scdn.co/image/ab67616d0000b2731f377fca5b39a58ee3728e9b', 'The Scrantones are an American rock band known for their song ''The Office Theme,'' which was used as the theme for the television show The Office. Their music blends elements of rock and pop, creating a catchy and memorable sound. The Scrantones'' contribution to television music has helped define the sound of workplace comedies.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (117, 'dashiin', '22qwq4EH17QsRkZWMEhelR', NULL, 'Dashiin is an American composer known for creating the theme for the television show Breaking Bad. His work in television music blends elements of electronic and orchestral music, creating a unique and haunting sound. Dashiin''s contributions to the genre have had a lasting impact on the sound of crime dramas.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (118, 'michael giacchino', '4kLvhMAuCloLxoP1aVM7Lr', 'https://i.scdn.co/image/ab6761610000e5eb9945209ac13720afd7eea2e3', 'Michael Giacchino is an American composer known for his work on film and television scores, including the themes for Lost and Up. His compositions often blend elements of orchestral and electronic music, creating a sophisticated and emotive sound. Giacchino''s influence on film and television music is significant, with his themes remaining popular and influential.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (119, 'massive attack', '6FXMGgJwohJLUSr5nVlf9X', 'https://i.scdn.co/image/c8bbeedb05f38ae5cb982a7daf4bf7129cca892c', 'Massive Attack are a British electronic music group known for their song ''Teardrop,'' which was used as the theme for House. Their music blends elements of trip-hop, electronica, and ambient sounds, creating a unique and atmospheric style. Massive Attack''s contribution to television music has helped define the sound of medical dramas.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (120, 'horace andy', '2ieAXAuLe6qQ3RJsqCxpoC', 'https://i.scdn.co/image/ab6772690000c46ca60968641586880e27d0daff', 'Horace Andy is a Jamaican reggae singer known for his work with Massive Attack, including the song ''Angel,'' which was used as the theme for Peaky Blinders. His distinctive vocal style and collaborations with various artists have made him a notable figure in reggae and electronic music. Andy''s contribution to television music has helped bring reggae to a wider audience.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (121, 'sean callery', '1mSdzR53wTsiokwyE8BJkl', 'https://i.scdn.co/image/ab6761610000e5eb6bd6ed70bbedcd153d6f5aa0', 'Sean Callery is an American composer known for creating the themes for 24 and Homeland. His work in television music blends elements of electronic and orchestral music, creating a unique and intense sound. Callery''s contributions to the genre have had a lasting impact on the sound of action and thriller shows.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (122, 'tom waits', '7x83XhcMbOTl1UdYsPTuZM', 'https://i.scdn.co/image/ab6761610000e5eb4679f0c1c8f862730c0b5109', 'Tom Waits is an American singer-songwriter known for his distinctive gravelly voice and eclectic style, blending elements of blues, jazz, and rock. He contributed the song ''Way Down in the Hole,'' which was used as the theme for The Wire. Waits'' contribution to television music has helped define the sound of crime dramas.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (123, 'dave porter', '1WkfFuCfD2BnsiyPElbEv5', 'https://i.scdn.co/image/ab6761610000e5eb7cbfba01b0dd0bc6ba7ac3e5', 'Dave Porter is an American composer known for creating the theme for Breaking Bad and its spin-off Better Call Saul. His work in television music blends elements of electronic and orchestral music, creating a unique and haunting sound. Porter''s contributions to the genre have had a lasting impact on the sound of crime dramas.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (124, 'rjd2', '1O3ZOjqFLEnbpZexcRjocn', 'https://i.scdn.co/image/ab6772690000c46c2e0662f18cc4b8676f3ecedd', 'RJD2 is an American musician and producer known for his work in hip-hop and electronic music. He contributed the song ''A Beautiful Mine,'' which was used as the theme for Mad Men. RJD2''s contribution to television music has helped define the sound of period dramas.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (125, 'jace everett', '47DQBkDU2VieRG0aJUcPJs', 'https://i.scdn.co/image/ab6761610000e5eb1e063ca95f9cfc5f1322cd2e', 'Jace Everett is an American singer-songwriter known for his song ''Bad Things,'' which was used as the theme for True Blood. His music blends elements of country and rock, creating a unique and atmospheric sound. Everett''s contribution to television music has helped define the sound of supernatural dramas.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (126, 'rolfe kent', '3B0bZAXnHTpGuPsuQo5fEd', 'https://i.scdn.co/image/ab6761610000e5ebd77a92a28c37f7bb9de45dba', 'Rolfe Kent is an American composer known for his work on film and television scores, including the themes for Dexter and Legally Blonde. His compositions often blend elements of orchestral and electronic music, creating a sophisticated and emotive sound. Kent''s influence on film and television music is significant, with his themes remaining popular and influential.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (127, 'malvina reynolds', '5fhMeS3lpUqUpTNuAxU2rN', 'https://i.scdn.co/image/ab67616d0000b2737cdea96511f9e03e3b1b1308', 'Malvina Reynolds was an American folk singer and songwriter known for her song ''Little Boxes,'' which was used as the theme for Weeds. Her music often addressed social and political issues, blending elements of folk and protest songs. Reynolds'' contribution to television music has helped bring folk music to a wider audience.', false);
INSERT INTO core_tables.artist (id, artist_name, spotify_artist_id, artist_artwork, artist_description, not_on_spotify) VALUES (128, 'mark mothersbaugh', '5sEDTHJJyDEWVFx99hGSIb', 'https://i.scdn.co/image/ab6761610000e5ebd707bc90aea4229d20d91682', 'Mark Mothersbaugh is an American composer, musician, and singer known for his work on film and television scores, including the themes for The Lego Movie and Rugrats. His compositions often blend elements of rock, pop, and electronic music, creating a unique and playful sound. Mothersbaugh''s influence on film and television music is significant, with his themes remaining popular and influential.', false);


--
-- Name: artist_id_seq; Type: SEQUENCE SET; Schema: core_tables; Owner: postgres
--

SELECT pg_catalog.setval('core_tables.artist_id_seq', 128, true);


--
-- PostgreSQL database dump complete
--

