--
-- PostgreSQL database dump
--

-- Dumped from database version 17.4
-- Dumped by pg_dump version 17.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Data for Name: track_ranking; Type: TABLE DATA; Schema: ranking_tables; Owner: postgres
--

INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (2, 1, 1, 1, 1, 'Ranked #1 in the 2010s, ''Cruise'' by Florida Georgia Line from the album Here''s To The Good Times is a country hit that''ll get you moving!', '2025-07-26');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (3, 2, 1, 1, 2, 'At #2 in the 2010s, Thomas Rhett''s ''Die A Happy Man'' from the album Tangled Up is a country ballad that tugs at the heartstrings.', '2025-07-26');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (4, 3, 2, 1, 1, 'Kicking off the 2000s country hits at rank 1, Lee Ann Womack''s ''I Hope You Dance'' from the album I Hope You Dance invites us to live fully!', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (5, 4, 2, 1, 2, 'Dramatic and poignant, Alan Jackson''s ''Where Were You When the World Stopped Turning'' from the album Drive captures a nation''s grief, ranking 2 in the 2000s country charts.', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (6, 5, 2, 1, 3, 'Did you know? Lonestar''s ''Amazed'' from the album Lonely Grill, a romantic ballad, secured the 3rd spot in the 2000s country music scene!', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (7, 6, 2, 1, 4, 'Patriotic fervor hits the charts at number 4 with Toby Keith''s ''Courtesy of the Red, White and Blue (The Angry American)'' from the album Unleashed.', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (8, 7, 2, 1, 5, 'Alan Jackson strikes again at rank 5 with ''It''s Five O''Clock Somewhere'' from the album Greatest Hits Volume II, a playful anthem for early drinkers!', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (9, 8, 2, 1, 6, 'Breaking the mold at number 6, Gretchen Wilson''s ''Redneck Woman'' from the album Here For The Party celebrates unapologetic country pride.', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (10, 9, 2, 1, 7, 'Saddle up for fun! Big and Rich''s ''Save a Horse (Ride a Cowboy)'' from the album Horse of a Different Color gallops to the 7th spot in the 2000s.', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (11, 10, 2, 1, 8, 'Sara Evans washes into the 8th position with ''Suds in the Bucket'' from the album Restless, a fresh take on love and laundry!', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (12, 11, 2, 1, 9, 'As the sun sets on the 9th rank, Kenny Chesney''s ''When the Sun Goes Down'' from the album When The Sun Goes Down serenades us into the night.', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (13, 12, 2, 1, 10, 'Closing the top 10 with a powerful message, Tim McGraw''s ''Live Like You Were Dying'' from the album Live Like You Were Dying inspires us to seize the day.', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (14, 13, 2, 1, 11, 'Ranked 11th in the 2000s, Lonestar''s ''I''m Already There'' from the album I''m Already There, is a country classic that tugs at the heartstrings.', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (15, 14, 2, 1, 12, 'Crack open a cold one with Toby Keith''s ''Beer For My Horses'', hitting number 12 in the 2000s country charts, straight from the album Unleashed!', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (16, 15, 2, 1, 13, 'Did you know Rascal Flatts'' ''Mayberry'' ranked 13th in the 2000s? This country gem is featured on the album Melt.', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (17, 16, 2, 1, 14, 'Bless your ears with Rascal Flatts'' ''Bless The Broken Road'', a touching country hit from the 2000s, ranking 14th, from the album Feels Like Today.', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (18, 17, 2, 1, 15, 'Keith Urban''s ''Days Go By'' cruises into the 15th spot in the 2000s country rankings, a smooth ride from the album Be Here.', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (19, 18, 2, 1, 16, 'Feel the charm of Keith Urban''s ''Somebody Like You'', securing the 16th rank in the 2000s country scene, from the album Golden Road.', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (20, 19, 2, 1, 17, 'Keith Urban''s ''You''ll Think Of Me'' clinches the 17th position in the 2000s, a poignant country tune from the album Golden Road.', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (21, 20, 2, 1, 18, 'Rascal Flatts keeps moving with ''I''m Movin'' On'', ranking 18th in the 2000s country hits, from their self-titled album Rascal Flatts.', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (22, 21, 2, 1, 19, 'Rascal Flatts reflects on ''These Days'', landing at number 19 in the 2000s country charts, featured on the album Melt.', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (23, 22, 2, 1, 20, 'Rev up for Rascal Flatts'' ''Fast Cars And Freedom'', speeding to the 20th spot in the 2000s, from the album Feels Like Today.', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (24, 23, 2, 1, 21, 'Ranked 21 in the 2000s, ''What Hurts The Most'' by Rascal Flatts from the album Me And My Gang is a country classic that tugs at the heartstrings!', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (25, 24, 2, 1, 22, 'Dive into the 2000s with ''My Wish'' by Rascal Flatts, hitting rank 22 in country music, straight from the album Me And My Gang.', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (26, 25, 2, 1, 23, 'At number 23, ''Stand'' by Rascal Flatts from the album Life Is A Highway: Refueled Duets, showcases their enduring presence in 2000s country music.', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (27, 26, 2, 1, 24, 'Feel the thrill of the open road with ''Life Is A Highway'' by Rascal Flatts, ranking 24 in the 2000s country genre, from Me And My Gang.', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (28, 27, 2, 1, 25, 'Discover the touching story of ''Skin Sarabeth'' by Rascal Flatts, ranked 25 in the 2000s, featured on the album Feels Like Today.', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (29, 28, 2, 1, 26, 'Brad Paisley''s ''She''s Everything'' captures hearts at rank 26, a 2000s country gem from the album Time Well Wasted.', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (30, 29, 2, 1, 27, 'Experience the poignant ''Whiskey Lullaby'' by Brad Paisley, ranking 27 in the 2000s country charts, from the album Hits Alive.', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (31, 30, 2, 1, 28, 'Get down and dirty with ''Mud On The Tires'' by Brad Paisley, securing spot 28 in the 2000s, from the album Mud On The Tires.', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (32, 31, 2, 1, 29, 'Raise a glass to ''Alcohol'' by Brad Paisley, a fun track that reached rank 29 in the 2000s, from Time Well Wasted.', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (33, 32, 2, 1, 30, 'Laugh along with ''Ticks'' by Brad Paisley, hitting number 30 in the 2000s country scene, from the album 5th Gear.', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (34, 33, 2, 1, 31, 'Dive into the 31st-ranked country hit of the 2000s, ''Letter to Me'' by Brad Paisley, from the album 5th Gear. It''s a playful reflection on life''s lessons!', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (35, 34, 2, 1, 32, 'At number 32, ''Online'' by Brad Paisley from 5th Gear takes the stage. This 2000s country track humorously explores the digital world.', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (36, 35, 2, 1, 33, 'Brad Paisley''s ''Waitin on a Woman'' ranks 33rd in the 2000s country charts. From the album Time Well Wasted, it''s a touching ode to patience.', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (37, 36, 2, 1, 34, 'Feel the romance with ''Then'' by Brad Paisley, hitting the 34th spot in the 2000s country genre. It''s from the album American Saturday Night!', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (38, 37, 2, 1, 35, 'Celebrate the 35th-ranked ''American Saturday Night'' by Brad Paisley. This 2000s country anthem, from the album of the same name, is pure fun!', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (39, 38, 2, 1, 36, 'Quench your thirst for great music with ''Water'' by Brad Paisley, ranked 36th in the 2000s country scene. From American Saturday Night, it''s refreshing!', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (40, 39, 2, 1, 37, 'Step into the future with Brad Paisley''s ''Welcome to the Future'', the 37th-ranked track in the 2000s country genre, from American Saturday Night.', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (41, 40, 2, 1, 38, 'Discover the 38th-ranked ''Anything Like Me'' by Brad Paisley. This 2000s country gem from Hits Alive is a playful nod to youthful antics.', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (42, 41, 2, 1, 39, 'Explore the world with Brad Paisley''s ''The World'', ranking 39th in the 2000s country charts. From Time Well Wasted, it''s a global journey!', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (43, 42, 2, 1, 40, 'Start a band with Brad Paisley''s ''Start a Band'', the 40th-ranked hit from the 2000s country genre. From the album Play, it''s a musical invitation!', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (44, 43, 2, 1, 41, 'Ranked 41 in the 2000s, ''Remind Me'' by Brad Paisley from the album ''This Is Country Music'' is a country gem that''ll stick in your mind!', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (45, 44, 2, 1, 42, 'Get ready for a chuckle with ''I''m Gonna Miss Her (The Fishin'' Song)'' by Brad Paisley, ranked 42 in the 2000s, from the album ''Part II''.', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (46, 45, 2, 1, 43, 'Did you know ''Celebrity'' by Brad Paisley, ranked 43 in the 2000s, comes from the album ''Mud On The Tires''? A country hit with a twist!', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (47, 46, 2, 1, 44, 'Brad Paisley''s ''Little Moments'', ranked 44 in the 2000s, also from ''Mud On The Tires'', captures the sweet side of country life.', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (48, 47, 2, 1, 45, 'Starting at rank 45 in the 2000s, ''Me Neither'' by Brad Paisley from ''Who Needs Pictures'' is a playful country tune you''ll love.', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (49, 48, 3, 1, 1, 'Kicking off the 2000s pop charts at number 1, Beyonce''s ''Crazy In Love'' from the album Dangerously In Love set the decade ablaze!', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (50, 49, 3, 1, 2, 'At number 2, Kelly Clarkson''s ''Since U Been Gone'' from Breakaway rocked the 2000s pop scene with its empowering vibe.', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (51, 50, 3, 1, 3, 'Did you know? Outkast''s ''Hey Ya'' from Speakerboxxx/The Love Below clinched the 3rd spot in the 2000s pop rankings!', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (53, 52, 3, 1, 5, 'Usher''s ''Yeah'' from Confessions (Expanded Edition) grooves its way to number 5 in the 2000s pop charts, unforgettable!', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (54, 53, 3, 1, 6, 'Feel the energy with Black Eyed Peas'' ''I Gotta Feeling'' from THE E.N.D. (THE ENERGY NEVER DIES), hitting number 6 in 2000s pop.', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (55, 54, 3, 1, 7, 'Beyonce strikes again at number 7 with ''Single Ladies (Put a Ring on It)'' from I AM...SASHA FIERCE, a 2000s pop anthem.', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (56, 55, 3, 1, 8, 'Lady Gaga''s ''Poker Face'' from The Fame poker-faced its way to the 8th spot in the 2000s pop rankings, iconic!', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (57, 56, 3, 1, 9, 'Rihanna''s ''Umbrella'' from Good Girl Gone Bad sheltered at number 9 in the 2000s pop charts, a stormy hit.', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (58, 57, 3, 1, 10, 'Gwen Stefani''s ''Hollaback Girl'' from Love. Angel. Music. Baby. (Deluxe Version) hollered to the 10th spot in 2000s pop, fierce!', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (59, 58, 3, 1, 11, 'Dive into the 2000s with Britney Spears'' ''Toxic'', ranked 11th, a pop sensation from the album In The Zone that''ll get you hooked!', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (60, 59, 3, 1, 12, 'Feel the power of Beyonce''s ''Irreplaceable'', a pop anthem from the 2000s, ranking at 12, featured on the album B''Day.', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (61, 60, 3, 1, 13, 'Get low with Flo Rida''s ''Low'', a catchy pop hit from the 2000s, ranking 13th, and found on the album Mail on Sunday.', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (62, 61, 3, 1, 14, 'Experience the emotional depth of Leona Lewis''s ''Bleeding Love'', a pop ballad from the 2000s, ranking 14th, from the album Spirit.', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (63, 62, 3, 1, 15, 'Boom into the 2000s with Black Eyed Peas'' ''Boom Boom Pow'', a pop explosion ranking 15th, from THE E.N.D. (THE ENERGY NEVER DIES).', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (64, 63, 3, 1, 16, 'Indulge in the sweet sounds of 50 Cent''s ''Candy Shop'', a pop track from the 2000s, ranking 16th, on the album The Massacre.', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (65, 64, 3, 1, 17, 'Dance the night away with Lady Gaga''s ''Just Dance'', a pop hit from the 2000s, ranking 17th, featured on The Fame album.', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (66, 65, 3, 1, 18, 'Savor the flavor of Lil Wayne''s ''Lollipop'', a pop delight from the 2000s, ranking 18th, from Tha Carter III (MTV Bonus Version).', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (67, 66, 3, 1, 19, 'Enter the world of Rihanna''s ''Disturbia'', a pop thriller from the 2000s, ranking 19th, on the album Good Girl Gone Bad: Reloaded.', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (68, 67, 3, 1, 20, 'Turn up the heat with Nelly''s ''Hot in Herre'', a pop classic from the 2000s, ranking 20th, from the album Nellyville.', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (69, 68, 3, 1, 21, 'Ranked 21 in the 2000s, ''Baby Boy'' by Beyonce from the album Dangerously In Love is a pop gem that''ll make you dance!', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (70, 69, 3, 1, 22, 'Feel the beat with ''In Da Club'' by 50 Cent, hitting rank 22 in the 2000s pop charts, from the album Get Rich Or Die Tryin''.', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (71, 70, 3, 1, 23, 'Ignite your spirit with ''Firework'' by Katy Perry, soaring to rank 23 in the 2000s, from the album Teenage Dream.', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (72, 71, 3, 1, 24, 'Did you know ''Tik Tok'' by Kesha, from the album TiK-Tok - Remixes, rocked the 2000s pop scene at rank 24?', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (73, 72, 3, 1, 25, 'Experience the drama of ''Bad Romance'' by Lady Gaga, a 2000s pop hit at rank 25, from The Fame Monster (Deluxe Edition).', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (74, 73, 3, 1, 26, 'Get ready to explode with ''Dynamite'' by Taio Cruz, a pop sensation from the 2000s, ranking 26, from the album Rokstarr.', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (75, 74, 3, 1, 27, 'Katy Perry''s ''I Kissed A Girl'' from One Of The Boys, a playful pop tune, reached rank 27 in the 2000s.', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (76, 75, 3, 1, 28, 'Fall in love with ''Love Story'' by Taylor Swift, a romantic pop ballad from Fearless (Taylor''s Version), ranking 28 in the 2000s.', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (77, 76, 3, 1, 29, 'You''ll feel like you belong with ''You Belong With Me'' by Taylor Swift, a 2000s pop hit at rank 29, from Fearless (Taylor''s Version).', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (78, 77, 3, 1, 30, 'Celebrate the urban vibe of ''Empire State of Mind'' by Jay-Z, ranking 30 in the 2000s pop charts, from The Blueprint 3.', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (79, 78, 3, 1, 31, 'Ranked 31 in the 2000s, Shakira''s ''Hips Don''t Lie'' from the album Oral Fixation, Vol. 2 (Expanded Edition) is a pop sensation that got everyone moving!', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (80, 79, 3, 1, 32, 'Justin Timberlake''s ''SexyBack'' stormed the charts at number 32 in the 2000s, a pop anthem from FutureSex/LoveSounds that redefined cool.', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (81, 80, 3, 1, 33, 'Did you know ''Promiscuous'' by Nelly Furtado hit rank 33 in the 2000s? This pop hit from the album Loose was all over the radio!', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (82, 81, 3, 1, 34, 'Sean Paul''s ''Temperature'' soared to number 34 in the 2000s, a fiery pop track from The Trinity that heated up dance floors everywhere.', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (83, 82, 3, 1, 35, 'Avril Lavigne''s ''Complicated'' captured hearts at rank 35 in the 2000s, a pop gem from Let Go that spoke to a generation.', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (84, 83, 3, 1, 36, 'Alicia Keys'' ''Fallin'''' touched souls, ranking 36 in the 2000s, a soulful pop ballad from Songs In A Minor that''s timeless.', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (85, 84, 3, 1, 37, 'Mary J. Blige''s ''Family Affair'' was a family reunion at rank 37 in the 2000s, a pop classic from No More Drama that brought us together.', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (86, 85, 3, 1, 38, 'Outkast''s ''Ms. Jackson'' apologized its way to number 38 in the 2000s, a poignant pop track from Stankonia that resonated deeply.', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (87, 86, 3, 1, 39, 'Snoop Dogg''s ''Drop It Like It''s Hot'' burned up the charts at rank 39 in the 2000s, a cool pop hit from R&G (Rhythm & Gangsta): The Masterpiece.', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (52, 51, 3, 1, 40, 'Kanye West''s ''Gold Digger'' dug its way to number 40 in the 2000s, a catchy pop tune from Late Registration that''s pure gold.', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (88, 87, 3, 1, 41, 'Dive into the 41st-ranked pop hit of the 2000s, ''Lose Yourself'' by Eminem, from the album Curtain Call: The Hits (Deluxe Edition). It''s a must-listen!', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (89, 88, 3, 1, 42, 'Feel the energy with ''Without Me'' by Eminem, ranking 42 in the 2000s pop charts, from The Eminem Show. It''s a classic you can''t miss!', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (90, 89, 3, 1, 43, 'Did you know ''Clocks'' by Coldplay, from A Rush of Blood to the Head, hit the 43rd spot in the 2000s pop genre? It''s timeless!', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (91, 90, 3, 1, 44, 'Experience the drama of ''Viva La Vida'' by Coldplay, ranking 44 in the 2000s pop charts, from Viva La Vida or Death and All His Friends. Epic!', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (92, 91, 3, 1, 45, 'Get ready to be moved by ''Chasing Cars'' by Snow Patrol, the 45th-ranked pop song of the 2000s, from Eyes Open. It''s pure emotion!', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (93, 92, 3, 1, 46, 'Discover the life-saving anthem ''How to Save a Life'' by The Fray, hitting 46 in the 2000s pop rankings, from How To Save A Life. Inspiring!', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (94, 93, 4, 1, 1, 'Kicking off the 2000s rock scene at #1, ''How You Remind Me'' by Nickelback from the album Silver Side Up rocks the charts!', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (95, 94, 4, 1, 2, 'Dive into the drama of the 2000s with ''In the End'' by Linkin Park, ranking #2, from the album Hybrid Theory (Bonus Edition).', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (96, 95, 4, 1, 3, 'Did you know? ''Boulevard of Broken Dreams'' by Green Day, from American Idiot (20th Anniversary Deluxe Edition), hit #3 in the 2000s rock genre!', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (97, 96, 4, 1, 4, 'Feel the energy of ''Dani California'' by Red Hot Chili Peppers, soaring to #4 in the 2000s, from the album Stadium Arcadium.', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (98, 97, 4, 1, 5, 'Linkin Park strikes again with ''Numb'' at #5, a 2000s rock anthem from the album Meteora.', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (99, 98, 4, 1, 6, 'Green Day''s ''American Idiot'' not only rocked the 2000s at #6 but also defined a generation, from the album American Idiot.', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (100, 99, 4, 1, 7, '3 Doors Down''s ''Kryptonite'' powered its way to #7 in the 2000s rock charts, from the album The Better Life.', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (101, 100, 4, 1, 8, 'Papa Roach''s ''Last Resort'' screamed to #8 in the 2000s, a rock classic from the album Infest.', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (102, 101, 4, 1, 9, 'Red Hot Chili Peppers groove with ''By the Way'' at #9, a 2000s hit from By the Way (Deluxe Edition).', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (103, 102, 4, 1, 10, 'The White Stripes'' ''Seven Nation Army'' marches to #10, a 2000s rock staple from the album Elephant.', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (104, 103, 4, 1, 11, 'Ranked 11th in the 2000s, ''Mr Brightside'' by The Killers rocks from the album Hot Fuss, igniting stages with its infectious energy!', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (105, 104, 4, 1, 12, 'At number 12, ''Drops of Jupiter (Tell Me)'' by Train, from the album Drops Of Jupiter, soars through the 2000s rock scene.', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (106, 105, 4, 1, 13, 'Did you know? ''Hanging by a Moment'' by Lifehouse, ranked 13th, defined 2000s rock from the album No Name Face.', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (107, 106, 4, 1, 14, 'Feel the pulse of the 2000s with ''The Middle'' by Jimmy Eat World, hitting rank 14, straight from Bleed American!', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (108, 107, 4, 1, 15, 'Drama unfolds with ''I Write Sins Not Tragedies'' by Panic! at the Disco, securing 15th spot, from A Fever You Can''t Sweat Out.', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (109, 108, 4, 1, 16, 'Crank up ''Feel Good Inc'' by Gorillaz, a 16th ranker in the 2000s rock genre, from the album Demon Days.', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (110, 109, 4, 1, 17, 'The Killers strike again with ''Somebody Told Me'', ranking 17th, rocking out from the album Hot Fuss in the 2000s.', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (111, 110, 4, 1, 18, 'Embrace the raw energy of ''When I''m Gone'' by 3 Doors Down, at 18th place, from Away From The Sun in the 2000s rock era.', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (112, 111, 4, 1, 19, 'Dare to groove with ''Dare'' by Gorillaz, clinching the 19th spot, a 2000s rock hit from Demon Days.', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (113, 112, 4, 1, 20, 'Everlong by Foo Fighters, ranked 20th, remains a timeless 2000s rock anthem from The Colour And The Shape.', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (114, 113, 4, 1, 21, 'Dive into the 2000s rock scene with ''Best of You'' by Foo Fighters, ranked 21, from the album In Your Honor!', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (115, 89, 4, 1, 22, 'Feel the pulse of the 2000s with ''Clocks'' by Coldplay, hitting rank 22, from the album A Rush of Blood to the Head.', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (116, 114, 4, 1, 23, 'Experience the healing power of ''Fix You'' by Coldplay, a 2000s rock gem at rank 23, from the album X&Y.', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (117, 90, 4, 1, 24, 'Celebrate life with ''Viva La Vida'' by Coldplay, a vibrant 2000s rock track at rank 24, from the album Viva La Vida or Death and All His Friends.', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (118, 115, 4, 1, 25, 'Bask in the glow of ''Yellow'' by Coldplay, a mellow 2000s rock classic at rank 25, from the album Parachutes.', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (119, 116, 4, 1, 26, 'Discover the reason behind the hit ''The Reason'' by Hoobastank, a 2000s rock anthem at rank 26, from the album The Reason (20th Anniversary).', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (120, 117, 4, 1, 27, 'Get electrified with ''Numb/Encore'' by Linkin Park, a dynamic 2000s rock mash-up at rank 27, from the album Numb / Encore: MTV Ultimate Mash-Ups Presents Collision Course.', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (121, 118, 4, 1, 28, 'Embrace the haunting beauty of ''My Immortal'' by Evanescence, a 2000s rock ballad at rank 28, from the album Fallen.', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (122, 119, 4, 1, 29, 'Let ''Bring Me to Life'' by Evanescence awaken your senses, a powerful 2000s rock track at rank 29, from the album Fallen.', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (123, 82, 4, 1, 30, 'Unravel the complexities of ''Complicated'' by Avril Lavigne, a catchy 2000s rock tune at rank 30, from the album Let Go.', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (124, 120, 4, 1, 31, 'Dive into the 2000s rock scene with ''Sk8er Boi'' by Avril Lavigne, ranked 31, from the album Let Go. It''s a playful anthem that defined a generation!', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (125, 121, 4, 1, 32, 'Feel the emotional depth of ''I''m With You'', ranked 32, a rock ballad by Avril Lavigne from the album Let Go. It''s a dramatic journey through the 2000s.', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (126, 122, 4, 1, 33, 'Did you know ''Here Without You'' by 3 Doors Down, ranked 33, from the album Away From The Sun, was a rock hit in the 2000s? Trivia time!', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (127, 123, 4, 1, 34, 'Experience the intensity of ''The Pretender'', ranked 34, a rock masterpiece by Foo Fighters from the album Echoes, Silence, Patience & Grace. It''s a thrilling ride!', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (128, 124, 4, 1, 35, 'Get ready for ''Chop Suey!'' by System of a Down, ranked 35, a rock explosion from the album Toxicity. It''s a wild trip through the 2000s!', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (129, 125, 4, 1, 36, 'Unleash the power of ''Toxicity'', ranked 36, another rock gem by System of a Down from the album Toxicity. It''s a dramatic showcase of the 2000s!', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (130, 126, 4, 1, 37, 'Rock out with ''BYOB'' by System of a Down, ranked 37, from the album Mezmerize. It''s a playful yet powerful statement from the 2000s!', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (131, 127, 4, 1, 38, 'Feel the melancholy of ''Lonely Day'', ranked 38, a rock ballad by System of a Down from the album Hypnotize. It''s a dramatic reflection of the 2000s.', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (132, 128, 4, 1, 39, 'Dance to the beat of ''Take Me Out'' by Franz Ferdinand, ranked 39, a rock hit from the album Franz Ferdinand. It''s a playful invitation to the 2000s!', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (133, 129, 4, 1, 40, 'Explore the indie rock vibes of ''Maps'' by Yeah Yeah Yeahs, ranked 40, from the album Fever To Tell (Deluxe Remastered). It''s a trivia-worthy track from the 2000s!', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (134, 130, 4, 1, 41, 'Ranked 41 in the 2000s, ''Float On'' by Modest Mouse rocks from the album Good News For People Who Love Bad News. It''s a must-listen!', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (135, 131, 4, 1, 42, 'At number 42, Maroon 5''s ''Harder to Breathe'' from the 2000s rock scene, featured on Songs About Jane: 10th Anniversary Edition, hits hard.', '2025-07-24');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (136, 132, 5, 1, 2, 'Did you know? ''ill be there for you'' by The Rembrandts, also from L.P., secured the #2 spot among 2000s TV Themes.', '2025-07-25');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (137, 133, 5, 1, 3, 'Climbing to #3, ''where everybody knows your name'' by Gary Portnoy from the album Keeper, is a cherished tune in the 2000s TV Themes genre.', '2025-07-25');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (138, 134, 5, 1, 4, 'At #4, ''the fresh prince of belair'' by DJ Jazzy Jeff and The Fresh Prince from Greatest Hits, brings the 2000s TV Themes to life!', '2025-07-25');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (139, 135, 5, 1, 5, 'Securing the #5 spot, ''the golden girls'' by Andrew Gold from Movie Soundtrack - Songs from Film & Tv, is a heartwarming 2000s TV theme.', '2025-07-25');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (140, 136, 5, 1, 6, 'Ranked #6, ''the jeffersons'' by Janet DuBois from Movin'' On Up (From "The Jeffersons") [Piano Version], adds soul to the 2000s TV Themes.', '2025-07-25');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (141, 137, 5, 1, 7, 'At #7, ''the brady bunch'' by The Brady Bunch from It''s A Sunshine Day : The Best Of The Brady Bunch, captures the essence of 2000s TV Themes.', '2025-07-25');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (142, 138, 5, 1, 8, 'Coming in at #8, ''the munsters'' by Jack Marshall from The Munsters (Original Motion Picture Soundtrack), is a spooky hit in the 2000s TV Themes.', '2025-07-25');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (143, 139, 5, 1, 9, 'Ranked #9, ''the beverly hillbillies'' by Flatt and Scruggs from Town and Country, is a country classic among 2000s TV Themes.', '2025-07-25');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (144, 140, 5, 1, 10, 'At #10, ''the andy griffith show'' by Earle Hagen from Themes And Laughs From The Andy Griffith Show, rounds out the top 2000s TV Themes.', '2025-07-25');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (145, 141, 5, 1, 11, 'Dive into the eerie vibes of the 2000s with ''The Twilight Zone'' by Marius Constant, ranked 11, from the album ''Pops Out Of This World'', a classic in TV Themes!', '2025-07-25');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (146, 142, 5, 1, 12, 'Feel the thrill of the 2000s with ''Hawaii Five-O'' by The Ventures, hitting rank 12, straight from the album ''Hawaii Five-O'', a staple in TV Themes.', '2025-07-25');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (147, 143, 5, 1, 13, 'Embark on a secret mission with ''Mission Impossible'' by Lalo Schifrin, securing rank 13 in the 2000s, from the album ''More Mission: Impossible'', a TV Themes gem.', '2025-07-25');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (148, 144, 5, 1, 14, 'Step back into the cool 2000s with ''Peter Gunn'' by Henry Mancini, clinching rank 14, from the album ''Music From Peter Gunn'', a must-hear in TV Themes.', '2025-07-25');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (149, 145, 5, 1, 15, 'Get ready for some classic 2000s action with ''Dragnet'' by Walter Schumann, ranking at 15, from the album ''Best Film-Noir Music of the 1950s, Vol.1 (Remastered 2024)'', a TV Themes legend.', '2025-07-25');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (150, 146, 5, 1, 16, 'Slip into the suave 2000s with ''The Pink Panther Theme'' by Henry Mancini, at rank 16, from the album ''The Pink Panther - Original Soundtrack'', a TV Themes icon.', '2025-07-25');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (151, 147, 5, 1, 17, 'Unleash your inner superhero with the ''Batman Theme'' by Neal Hefti, soaring to rank 17 in the 2000s, from the album ''The Music Of DC Comics: Vol. 2'', a TV Themes classic.', '2025-07-25');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (152, 148, 5, 1, 18, 'Explore the final frontier with ''Star Trek'' by Alexander Courage, reaching rank 18 in the 2000s, from the album ''The Ultimate Star Trek'', a TV Themes staple.', '2025-07-25');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (153, 149, 5, 1, 19, 'Laugh along with the 2000s hit ''The Simpsons'' by Danny Elfman, at rank 19, from the album ''The City of Prague Philharmonic Orchestra Plays The Music Of Danny Elfman'', a TV Themes favorite.', '2025-07-25');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (154, 150, 5, 1, 20, 'Delve into the mysterious 2000s with ''X-Files'' by Mark Snow, at rank 20, from the album ''X Files - I Want To Believe / OST'', a haunting TV Themes track.', '2025-07-25');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (155, 151, 5, 1, 21, 'Dive into the 2000s with ''Law and Order'' by Mike Post, ranked 21st in TV Themes, from the album ''Inventions From The Blue Line''. It''s drama at its finest!', '2025-07-25');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (156, 152, 5, 1, 22, 'Feel the thrill of the 2000s with ''CSI: Crime Scene Investigation'' by The Who, hitting rank 22 in TV Themes, from the album ''Who''s Next (Deluxe Edition)''.', '2025-07-25');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (157, 153, 5, 1, 23, 'Get a taste of the 2000s with ''The Sopranos'' theme by Alabama 3, securing rank 23 in TV Themes, from the album ''The Wimmin from W.O.M.B.L.E, Vol. 2''.', '2025-07-25');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (158, 154, 5, 1, 24, 'Step into the political drama of the 2000s with ''The West Wing'' by W.G. Snuffy Walden, ranked 24th in TV Themes, from the album ''The West Wing (Original Television Soundtrack)''.', '2025-07-25');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (159, 155, 5, 1, 25, 'Experience the urgency of the 2000s with ''ER'' by James Newton Howard, clinching rank 25 in TV Themes, from the album ''Fantastic Beasts and Where to Find Them (Original Motion Picture Soundtrack)''.', '2025-07-25');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (160, 156, 5, 1, 26, 'Catch the cool vibes of the 2000s with ''The O.C.'' by Phantom Planet, landing at rank 26 in TV Themes, from the album ''The Guest (Expanded Edition)''.', '2025-07-25');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (161, 157, 5, 1, 27, 'Laugh through the 2000s with ''Scrubs'' by Lazlo Bane, humorously ranked 27th in TV Themes, from the album ''Scrubs''.', '2025-07-25');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (162, 158, 5, 1, 28, 'Enter the quirky world of the 2000s with ''The Office'' by The Scrantones, humorously ranked 28th in TV Themes, from the album ''The Office (Dashiin Remix)''.', '2025-07-25');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (163, 159, 5, 1, 29, 'Get lost in the mystery of the 2000s with ''Lost'' by Michael Giacchino, mysteriously ranked 29th in TV Themes, from the album ''Lost: The Final Season (Original Television Soundtrack)''.', '2025-07-25');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (164, 160, 5, 1, 30, 'Diagnose the beats of the 2000s with ''House'' by Massive Attack, clinically ranked 30th in TV Themes, from the album ''Лучшие хиты: Trip Hop''.', '2025-07-25');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (165, 161, 5, 1, 31, 'Dive into the 31st ranked TV theme of the 2000s, ''Desperate Housewives'' by Danny Elfman, from the album Desperate Housewives (TV Soundtrack). It''s a genre-defining tune!', '2025-07-25');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (166, 162, 5, 1, 32, 'Feel the tension with the 32nd ranked ''24'' theme by Sean Callery from the 2000s, featured on the album 24: The Game. A thrilling TV Themes classic!', '2025-07-25');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (167, 163, 5, 1, 33, 'Explore the gritty sound of ''The Wire'', ranked 33rd in the 2000s TV Themes, performed by Tom Waits from the album ...and all the pieces matter, Five Years of Music from The Wire (deluxe version).', '2025-07-25');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (168, 164, 5, 1, 34, 'Unleash the drama with ''Breaking Bad'', the 34th ranked track of the 2000s, composed by Dave Porter from the album Breaking Bad: Original Score from the Television Series. A must-hear in TV Themes!', '2025-07-25');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (169, 165, 5, 1, 35, 'Step back in time with ''Mad Men'', ranked 35th in the 2000s, brought to life by RJD2 from the album A Beautiful Mine (Mad Men Instrumental Theme) [From "Retrospective: The Music Of Mad M].', '2025-07-25');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (170, 166, 5, 1, 36, 'Sink your teeth into ''True Blood'', the 36th ranked TV theme of the 2000s, sung by Jace Everett from the album TRUE BLOOD (Music from the HBO® Original Series). A haunting melody!', '2025-07-25');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (171, 167, 5, 1, 37, 'Get a taste of suspense with ''Dexter'', ranked 37th in the 2000s TV Themes, crafted by Rolfe Kent from the album Dexter Season 4. It''s chillingly good!', '2025-07-25');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (172, 168, 5, 1, 38, 'Discover the quirky charm of ''Weeds'', the 38th ranked track from the 2000s, sung by Malvina Reynolds from the album Weeds (Music from the Original Series). A unique TV theme!', '2025-07-25');
INSERT INTO ranking_tables.track_ranking (id, track_id, decade_genre_id, tracklist_id, ranking, intro, ranking_date) VALUES (173, 169, 5, 1, 39, 'Experience the high life with ''Entourage'', ranked 39th in the 2000s, composed by Mark Mothersbaugh from the album The Royal Tenenbaums (Original Soundtrack). A stylish TV theme!', '2025-07-25');


--
-- Name: track_ranking_id_seq; Type: SEQUENCE SET; Schema: ranking_tables; Owner: postgres
--

SELECT pg_catalog.setval('ranking_tables.track_ranking_id_seq', 173, true);


--
-- PostgreSQL database dump complete
--

